"""
Alert model for cyber threats detected in unidirectional IP traffic.
Captures severity score, confidence, behavior classification, MITRE linkage, and source flow.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional, Any, Dict

from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    String,
    Uuid,
    JSON,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.flow import Flow
    from app.models.mitre import MitreMapping


class Alert(Base, TimestampMixin):
    """
    Threat Alert Model.
    Represents an actionable cyber defense alert generated by the AI detection engine
    from a source unidirectional flow telemetry record.
    """
    __tablename__ = "alerts"

    # Primary Key
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Source Flow Foreign Key (Required)
    flow_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("flows.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # MITRE ATT&CK Mapping Foreign Key (Optional)
    mitre_mapping_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("mitre_mappings.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Severity & Scores
    severity: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        default="MEDIUM",
        index=True,
    )  # 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'

    severity_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )  # Normalized score 0.0 - 10.0

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )  # AI model confidence 0.0 - 1.0

    # Threat Characterization
    behavior_class: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        index=True,
    )  # e.g., "DNS Exfiltration", "Unidirectional SYN Sweep", "Entropy Anomaly"

    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="NEW",
        index=True,
    )  # 'NEW', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'

    model_version: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="v1.0.0",
    )  # Tracks the specific AI inference model artifact used

    explanation: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=True,
        default=dict,
    )  # Explainable AI feature contributions (e.g. high entropy, abnormal packet size)

    # Alert generation timestamp
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships
    flow: Mapped["Flow"] = relationship(
        "Flow",
        back_populates="alerts",
        lazy="selectin",
    )

    mitre_mapping: Mapped[Optional["MitreMapping"]] = relationship(
        "MitreMapping",
        back_populates="alerts",
        lazy="selectin",
    )

    __table_args__ = (
        Index("idx_alerts_severity_status", "severity", "status"),
        Index("idx_alerts_timestamp_behavior", "timestamp", "behavior_class"),
    )

    def __repr__(self) -> str:
        aid = self.__dict__.get("id", "detached")
        sev = self.__dict__.get("severity", "unknown")
        bclass = self.__dict__.get("behavior_class", "unknown")
        conf = self.__dict__.get("confidence", 0.0)
        status = self.__dict__.get("status", "unknown")
        return (
            f"<Alert {aid} [{sev}] class={bclass} "
            f"conf={conf} status={status}>"
        )
